ACTIVE_SLEEP_TIME = 0.1

PASSIVE_SLEEP_TIME = 1

# Distances are in centimeters

# Settings for my garage
#RED_LED_MAX_DISTANCE = 20
#GREEN_LED_MAX_DISTANCE = 28
#YELLOW_LED_MAX_DISTANCE = 100
#ORANGE_LED_MAX_DISTANCE = 200


# Settings for Dad's garage
RED_LED_MAX_DISTANCE = 20
GREEN_LED_MAX_DISTANCE = 40
YELLOW_LED_MAX_DISTANCE = 100
ORANGE_LED_MAX_DISTANCE = 200